### PR TITLE
Fixing the ETC wiki link

### PR DESCRIPTION
**Pull request by vargasmontero**
Fixing the ETC wiki link

### CODE REVIEW

**Review by gitr0n1n — CHANGES_REQUESTED** [review]
This wiki does not appear to be associated with ETC anymore. I think we can close this issue.

**Comment by gitr0n1n** [comment]
@cseberino can close this issue. Not applicable anymore.

**Comment by gitr0n1n** [comment]
you can close this PR @TheEnthusiasticAs

**Comment by TheEnthusiasticAs** [comment]
I have no permission to close it, @gitr0n1n. @YazzyYaz could you pls close it? Thx

**Comment by gitr0n1n** [comment]
> This wiki does not appear to be associated with ETC anymore. I think we can close this issue.

probably don't want to merge this one and rather reject it.

**Pull request closed without merging**
